# Generated by Django 4.2.7 on 2023-12-05 16:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_remove_order_foodcartapp_last_na_c83b91_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercontents',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='количество'),
        ),
    ]
