# Generated by Django 4.2.8 on 2023-12-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_ordercontents_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'создан'), ('accepted', 'принят'), ('packed', 'собран'), ('shipped', 'доставлен')], db_index=True, default='created', max_length=20, verbose_name='статус заказа'),
            preserve_default=False,
        ),
    ]
