# Generated by Django 4.2.8 on 2023-12-21 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='available_restaurants',
            field=models.ManyToManyField(blank=True, to='foodcartapp.restaurant', verbose_name='доступные рестораны'),
        ),
        migrations.AddField(
            model_name='order',
            name='cooked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='foodcartapp.restaurant', verbose_name='готовящий ресторан'),
        ),
    ]
