# Generated by Django 4.2.7 on 2023-12-04 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0038_order_ordercontents_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='foodcartapp_last_na_c83b91_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='foodcartapp_phone_675d71_idx',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='last_name',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='phone',
            new_name='phonenumber',
        ),
        migrations.RenameField(
            model_name='ordercontents',
            old_name='item',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='ordercontents',
            old_name='amount',
            new_name='quantity',
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['lastname', 'firstname'], name='foodcartapp_lastnam_a2dab6_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['phonenumber'], name='foodcartapp_phonenu_5f4ceb_idx'),
        ),
    ]
