# Generated by Django 4.2.7 on 2023-12-07 23:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_alter_ordercontents_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercontents',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='стоимость позиции'),
            preserve_default=False,
        ),
    ]
