# Generated by Django 4.2.7 on 2023-12-07 23:54

from django.db import migrations
from django.db.models import F


def calculate_contents_price(apps, schema_editor):
    OrderContents = apps.get_model("foodcartapp", "OrderContents")

    orders = OrderContents.objects.prefetch_related("product")
    for order in orders.iterator():
        order.cost = F("product__price") * order.quantity
        order.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_ordercontents_cost'),
    ]

    operations = [
        migrations.RunPython(calculate_contents_price)
    ]
