# Generated by Django 4.2.8 on 2023-12-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('accepted', 'Принят'), ('packed', 'Собран'), ('shipped', 'Доставлен')], db_index=True, max_length=20, verbose_name='статус заказа'),
        ),
    ]
