# Generated by Django 4.2.8 on 2023-12-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_order_accepted_at_order_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличными'), ('online', 'Электронно')], db_index=True, default='cash', max_length=12, verbose_name='способ оплаты'),
        ),
    ]
