# Generated by Django 4.2.8 on 2023-12-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('accepted', 'Принят'), ('packed', 'Собран'), ('delivered', 'Доставлен')], db_index=True, default='created', max_length=20, verbose_name='статус заказа'),
        ),
    ]
