# Generated by Django 4.2.8 on 2024-03-20 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_order_available_restaurants_order_cooked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercontents',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='foodcartapp.product', verbose_name='товар'),
        ),
    ]
