services:
  # backend: 
  #   build: 
  #     context: ../../backend
  #   image: starburger_backend
  #   depends_on:
  #     frontend:
  #       condition: service_completed_successfully

  frontend:
    build: 
      context: ../../frontend
    volumes:
      - bundles:/opt/static-jinja/frontend/bundles


volumes:
  bundles:
