# Generated by Django 4.2.8 on 2024-01-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(unique=True, verbose_name='адрес')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='долгота')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='широта')),
                ('last_fetched', models.DateTimeField(verbose_name='дата проверки координат')),
            ],
        ),
    ]
